dbwebproj/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('u/', include('users.urls')),
    path('c/', include('community.urls')),
    path('p/', include('posts.urls')),
    path('', include('common.urls')),

]

handler404 = 'common.views.handler404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, re_path
from .views import (createReply_AJAX, delete, post, update, updateReply_AJAX)


# url patterns under ('p/')
urlpatterns = [
    
    # post urls
    path('<str:slug>/', post, name='post-detail'),
    path('<str:slug>/update/', update, name='post-update'),
    path('<str:slug>/delete/', delete, name='post-delete'),

    # reply create url
    path('<str:slug>/reply/', createReply_AJAX, name='reply-create'),

]

users/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, re_path
from .views import profile, userJoinedCommunities


# url patterns under ('u/')
urlpatterns = [

    # user/profile urls
    path('<str:username>/', profile, name='profile'),
    path('<str:username>/communities/', userJoinedCommunities, name='joined-communities'),

]

wroovie/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
import django.views.defaults as default_views

# main url patterns
urlpatterns = [

    # django admin urls
    path('admin/', admin.site.urls),

    # my app urls
    path('', include('common.urls')),
    path('u/', include('users.urls')),
    path('c/', include('community.urls')),
    path('p/', include('posts.urls')),
    
    # other app urls
    path('trixeditor/', include('trix.urls')),
    path('summernote/', include('django_summernote.urls')),
    
]

handler404 = 'common.views.handler404'

from common.views import handler404 as hndlr404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        re_path(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        re_path(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        re_path(r'^404/$', hndlr404, kwargs={'exception': Exception('Page not Found')}),
        re_path(r'^500/$', default_views.server_error),
    ]

community/models.py
import os
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Count, Max
from django.utils import timezone
from common.storage import OverwriteStorage
from common.utils import computeProminentColor, resizeImage


#####~~~~~ APP VARIABLES ~~~~~#####
BASE_PATH = "community"
DEFAULT_COMMUNITY_ICON_PATH = os.path.join(BASE_PATH, 'default_icon.png')

#####~~~~~ UTILITY FUNCTION ~~~~~#####
def CommunityIconSavePath(instance, filename):
    return os.path.join(BASE_PATH, instance.name, 'icon' + os.path.splitext(filename)[1])

#####~~~~~ UTILITY FUNCTION ~~~~~#####
def CommunityBannerSavePath(instance, filename):
    return os.path.join(BASE_PATH, instance.name, 'banner' + os.path.splitext(filename)[1])

#####~~~~~ MODEL ~~~~~#####
class Community(models.Model):
    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=25, unique=True)     # only alphabets (capital/small), no spaces
    title = models.CharField(max_length=50)                 # short tagline
    about = models.CharField(max_length=500)
    dt_creation = models.DateTimeField(default=timezone.now)
    # many-to-many relation attributes
    admins = models.ManyToManyField(User, related_name='administered_communities')
    members = models.ManyToManyField(User, related_name='joined_communities', through='Membership')
    # theming attributes
    icon = models.ImageField(default=DEFAULT_COMMUNITY_ICON_PATH, storage=OverwriteStorage(), upload_to=CommunityIconSavePath)
    banner = models.ImageField(null=True, blank=True, storage=OverwriteStorage(), upload_to=CommunityBannerSavePath)
    highlight_color_hex =  models.CharField(default='000000', max_length=8, blank=True) 

    def __str__(self):
        return f'{self.name} - {self.title}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # resize image and banner
        resizeImage(self.icon.path, 300, 300)
        if self.banner:
            resizeImage(self.banner.path, 500, 500)
        # set highlight color
        self.highlight_color_hex = computeProminentColor(self.icon.path)
        super().save(update_fields=['highlight_color_hex'])

    def get_top_posts(self, count = None):
        if count is None:
            return self.posts.all().annotate(count=(Count('upvotes__id')-Count('downvotes__id'))).order_by('-count', '-dt_creation') 
        else: 
            return self.posts.all().annotate(count=(Count('upvotes__id')-Count('downvotes__id'))).order_by('-count', '-dt_creation')[:count]
    
    def get_latest_posts(self, count = None):
        return self.posts.all() if count is None else self.posts.all()[:count]
    
    def get_top_post(self):
        return self.get_top_posts(1)
    
    def get_top_post_score(self):
        return self.posts.all().annotate(count=(Count('upvotes__id')-Count('downvotes__id'))).aggregate(Max('count'))['count__max']

    class Meta:
        ordering = ['-dt_creation']

#####~~~~~ (THROUGH) MODEL ~~~~~#####
class Membership(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    dt_join = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-dt_join']


# Community (FOLDER)
# -- comm1 (FOLDER)
# -- -- icon.png
# -- -- banner.png
# -- -- post_images (FOLDER)
# -- -- -- post1-pic1.png

# last_mod = models.DateTimeField(auto_now=True)  # last modified
# dtop = models.DateTimeField(auto_now_add=True)  # object creation (cannot be updated)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile
from django.forms import TextInput 


#####~~~~~ FORM ~~~~~#####
# user+profile registration form
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.count() > 0:
            raise forms.ValidationError("A profile with this email already exists.")
        return email

#####~~~~~ FORM ~~~~~#####
# user update form
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']

#####~~~~~ FORM ~~~~~#####
# profile update form
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'banner']

users/views.py
import logging
from django import forms
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.sites.models import Site
from django.core.exceptions import ValidationError
from django.core.mail import EmailMessage
from django.core.validators import validate_email
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from rest_framework import authentication, permissions
from .forms import ProfileUpdateForm, UserRegisterForm, UserUpdateForm
from .models import Profile
from .tokens import emailVerificationToken
from community.models import Membership
from common.views import getFeedContextMin

#####~~~~~ UTILITY FUNCTION ~~~~~#####
# sends an email to user-email
def sendEmailToUser(user_id, mail_subject, message, to_email):
    UserModel = get_user_model()
    try:        
        try:
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
        except Exception as e:
            logging.warning(f'Tried to send an invalid email: ${e}')    
    except UserModel.DoesNotExist:
        logging.warning("Tried to send email to non-existing user '%s'" % user_id)

#####~~~~~ UTILITY FUNCTION ~~~~~#####
# send email to user for verification
def sendAccountVerificationEmail(username=None):
    user = None
    # get user from db
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        # cannot find user, TODO throw some error
        return
    username = user.username
    email = user.email
    mail_subject = 'wroovie signup: Verify Your EMAIL Account'
    message = render_to_string('users/email_verify.html', {
        'user': user,
        'domain': Site.objects.get_current().domain,
        'uid':urlsafe_base64_encode(force_bytes(user.pk)),
        'token':emailVerificationToken.make_token(user),
    }) 
    sendEmailToUser(user.pk, mail_subject, message, email)

#####~~~~~ VIEW ~~~~~#####
# get user profile page
def profile(request, username):
    user = get_object_or_404(User, username=username)    
    req_page = request.GET.get('page')
    req_sort = request.GET.get('sort')

    page = "posts"
    sort = "top"

    if req_page is not None and req_page != "":
        if req_page == "comments":
            page = req_page
        elif request.user.is_authenticated:
            if req_page == 'upvoted' or req_page == "downvoted":
                page = req_page
            elif request.user == user:
                if req_page == 'saved':
                    page = req_page
                elif req_page == "editprofile":
                    return redirect('settings')
                elif user.administered_communities and req_page == "modpanel":
                    return redirect('modpanel')

    if req_sort is not None and req_sort != "":
        if req_sort == "latest":
            sort = req_sort

    context = {
        'profile_user': user,
        'profile': user.profile,
        'page': page,
        'sort': sort,
        'show_comm_info': True, # feed-view
    }
    
    # extra (sidebar) stuff
    if request.user == user:
        rec_memb = Membership.objects.filter(user=user).order_by('-dt_join')[:5]
        context['rec_memb'] = rec_memb
    return render(request, 'users/profile.html', context)

#####~~~~~ VIEW ~~~~~#####
# user and profile settings update view
@login_required
def settings(request):
    # warn user to verify email
    if not request.user.profile.email_verified:
        messages.warning(request, f'Please verify your email address.')
    if request.method == 'POST':
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if p_form.is_valid():
            p_form.save()
            messages.success(request, f'Your profile has been updated!')
            return redirect('profile', request.user.username)
        else:
            context = {
                'form': p_form,
                'profile_user': request.user,
                'profile': request.user.profile,
                'page': 'editprofile',
            }
            return render(request, 'users/profile.html', context)
    else:
        p_form = ProfileUpdateForm(instance=request.user.profile)
        context = {
            'form': p_form,
            'profile_user': request.user,
            'profile': request.user.profile,
            'page': 'editprofile',
        }
        return render(request, 'users/profile.html', context)

#####~~~~~ VIEW ~~~~~#####
# user moderator panel
# list of administered communities
@login_required
def modpanel(request):
    # warn user to verify email
    if not request.user.profile.email_verified:
        messages.warning(request, f'Please verify your email address.')

    if not request.user.administered_communities.all():
        return redirect('profile', request.user.username)

    communities = request.user.administered_communities.all()

    context = {
        'communities': communities,
        'profile_user': request.user,
        'profile': request.user.profile,
        'page': 'modpanel',
    }
    return render(request, 'users/profile.html', context)

#####~~~~~ VIEW ~~~~~#####
# list of joined communities
@login_required
def userJoinedCommunities(request, username):

    user = get_object_or_404(User, username=username)    

    if request.user != user:
        return redirect('profile', user.username)

    communities = request.user.joined_communities.all()

    context = {
        'communities': communities,
        'heading': 'Joined Communities',
        'empty_text': 'Its a little lonely here :('
    }
    context.update(getFeedContextMin(request))
    return render(request, 'community/community_list.html', context)

#####~~~~~ VIEW ~~~~~#####
# user login view
def login(request):
    if request.method == 'POST' and request.is_ajax():
        if request.user.is_authenticated:
            data = {'message': 'already logged in'}
            return JsonResponse(data)
        else:
            user = authenticate(username=request.POST['username'], password=request.POST['password'])
            data = {}
            if user is None:
                data = {'message': 'failure'}
                return JsonResponse(data)
            else:
                auth_login(request, user)
                data = {'message': 'success'}
                return JsonResponse(data)
    else:
        if request.user.is_authenticated:
            return redirect('home')
        else:
            return render(request, 'users/login.html', {'redirect_path': request.path})

#####~~~~~ VIEW ~~~~~#####
# logout is done using django's builT-in logout class-based view function (see common.urls)

#####~~~~~ VIEW ~~~~~#####
# user creation view
def register(request):
    if request.user.is_authenticated:
        return redirect("home")
    if request.method == 'POST' and request.is_ajax():
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']
        data = {
            'message':'',
            'error':'',
            'account':{}
        }
        # test email validity
        try:
            validate_email(email)
        except ValidationError as e:
            # email invalid
            data['message'] = 'invalid_email'
            print(e)
            data['error'] = e.messages
            return JsonResponse(data)    
        # test email availability
        try:
            match = User.objects.get(email=email)
        except User.DoesNotExist:
            # email available, hence test username
            # test username validity
            validate_username = UnicodeUsernameValidator()
            try:
                validate_username(username)
            except ValidationError as e:
                data['message'] = 'invalid_username'
                print(e.messages)
                data['error'] = e.messages
                return JsonResponse(data)
            # test username availability
            try:
                match = User.objects.get(username=username)
            except User.DoesNotExist:
                # username available, hence test password
                # test password validity
                try:
                    validate_password(password1)
                except ValidationError as e:
                    # password invalid
                    data['message'] = 'invalid_password'
                    print(e)
                    data['error'] = e.messages
                    return JsonResponse(data)
                # password valid, test password1 & password2 match
                if password1 == password2:
                    # passwords match
                    # all seems good, attempt account creation
                    user = get_user_model().objects.create_user(username=username, email=email, password=password1)
                    user.save()
                    # check if user's been created
                    try:
                        user = User.objects.get(username=username, email=email)
                    except User.DoesNotExist:
                        # account not created, unknown error
                        data['message'] = 'error'
                        data['error'] = ['Unknown error. User account not created.']
                        return JsonResponse(data)

templates/users/email_user_upgrade_instructor.html
{% autoescape off %}
    Hi {{ admin.username }},
    {{ user.username }} has submitted a request to become an Instructor.
    
    Kindly review the following User Profile to decide:
    http://{{ domain }}/user/{{ user.username }}

    Click the link below to provide {{ user.username }} with {{ request }} level authorities:
    http://{{ domain }}{% url 'user_process_upgrade_instructor' uidb64=uid token=token %}
{% endautoescape %}

templates/users/email_verify.html
{% autoescape off %}
    Hi {{ user.username }},
    Please click on the link below to finish your Sign-Up:
    https://{{ domain }}{% url 'email-verify' uidb64=uid token=token %}
{% endautoescape %}

templates/users/login.html
{% extends "common/base.html" %}
{% load static %}
{% load humanize %}

{% load extra_tags %}


{% block title %}
    Login - wroovie
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/base.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Inria+Sans:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nixie+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/login.css' %}">
{% endblock %}

<!-- override unnecessary blocks -->
{% block navbar %}
{% endblock %}
{% block modal %}
{% endblock %}
{% block base_stylesheets %}
{% endblock %}

{% block main %}


    <div class="main main-login">

        <div class="login-form-wrap">
            <div class="login-form">
                <div class="wlogo" style="cursor: pointer;" onclick="window.location.href='{% url 'home' %}'">
                    wroovie
                </div>

                <div class="heading">
                    Log In
                </div>
                

                <div class="container">
                    <form autocomplete="off">
                        {% csrf_token %}
                        <div class="inp-wrap username-box">
                            <input class="input-username" type="text" name="username" required="">
                            <label class="label-username">USERNAME</label>
                            <span></span>
                        </div>
                        <div class="inp-wrap password-box">
                            <input class="input-password" type="password" name="password" required="">
                            <label class="label-password">PASSWORD</label>
                            <span></span>
                        </div>

                        <div class="out-wrap">
                            <button type="submit" value="LOG IN" name="" class="login-btn enabled"> 
                                <div class="login-btn-text">LOG IN</div>
                                <div class="login-btn-loader loader" hidden=true></div>
                                <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="check" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="login-tick svg-inline--fa fa-check fa-w-16 fa-9x"><path fill="currentColor" d="M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997 26.207-9.997 36.204 0l36.203 36.204c9.997 9.997 9.997 26.206 0 36.204l-294.4 294.401c-9.998 9.997-26.207 9.997-36.204-.001z" class=""></path></svg>
                                <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="times" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 352 512" class="login-cross svg-inline--fa fa-times fa-w-11 fa-9x"><path fill="currentColor" d="M242.72 256l100.07-100.07c12.28-12.28 12.28-32.19 0-44.48l-22.24-22.24c-12.28-12.28-32.19-12.28-44.48 0L176 189.28 75.93 89.21c-12.28-12.28-32.19-12.28-44.48 0L9.21 111.45c-12.28 12.28-12.28 32.19 0 44.48L109.28 256 9.21 356.07c-12.28 12.28-12.28 32.19 0 44.48l22.24 22.24c12.28 12.28 32.2 12.28 44.48 0L176 322.72l100.07 100.07c12.28 12.28 32.2 12.28 44.48 0l22.24-22.24c12.28-12.28 12.28-32.19 0-44.48L242.72 256z" class=""></path></svg>

                            </button>
                            <div class="more-options">
                                or <a class="strong" href="{% url 'register' %}">Sign Up</a><br/>
                                <a class="small">Forgot Password?</a>
                            </div>
                        </div>
                        <div class="message-box" hidden=true>
                            No Message
                        </div>
                    </form>
                </div>
            </div>
        </div>
        
        <div class="background-wrap bg-1"></div>

        <div class="background-wrap bg-2"></div>

        <div class="background-wrap bg-6"></div>
    </div>

{% endblock %}

{% block js %}
{% endblock %}

{% block extrajs %}
    <script src="{% static 'common/js/jquery-3.4.1.min.js' %}" type="text/javascript"></script>
    <script defer src="{% static 'common/js/login.js' %}" type="text/javascript"></script>

{% endblock %}

templates/users/logout.html
{% extends "blog/base.html" %}

{% block content %}

    <h1>thisBlog</h1>

    <h2>You have been logged out of your account.</h2>

    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>

{% endblock content %}

templates/users/modpanel.html
<div class="comm-1-1">
                

    {% if not communities %}
    <span class="form-heading txt-brk">YOU DON'T MODERATE ANY COMMUNITIES</span> 
    {% else %}

    <span class="form-heading txt-brk">MODERATOR PANEL</span> 

        {% if communities %}
            <span class="form-subheading">COMMUNITIES YOU MODERATE</span> 
            
            {% include "community/community_list_min_mod.html" %}
        {% endif %}

        <div class="div-gap medium"></div>
    
    {% endif %}


</div>

templates/users/password_reset.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags  %}

{% block content %}

    <h1>thisBlog Password Reset</h1>

    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
            </div>
        </form>
    </div>

{% endblock content %}

templates/users/password_reset_complete.html
{% extends "blog/base.html" %}

{% block content %}

    <h1>thisBlog</h1>

    <div class="alert alert-info">
        Your password has been reset successfully.
    </div>
    <a href="{% url 'login' %}">Sign In Here</a>

{% endblock content %}

templates/users/password_reset_confirm.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags  %}

{% block content %}

    <h1>thisBlog Password Reset</h1>

    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>

{% endblock content %}

templates/users/password_reset_done.html
{% extends "blog/base.html" %}

{% block content %}

    <h1>thisBlog</h1>

    <div class="alert alert-info">
        An email has been sent with instructions to reset your password.
        <br/>
        Kindly check your email.
    </div>

{% endblock content %}

templates/users/settings.html

<div class="comm-1-1">
            
    <form action="{% url 'settings' %}" class="form-settings-user community-create-form" id="community-create" method="POST" enctype="multipart/form-data">
        <span class="form-heading">CUSTOMIZE YOUR PROFILE</span> 

        <div class="form-gap small"></div>
        {% csrf_token %}

        <span style="display: flex;" class="form-settings-user">
            <label class="create-community-label edit-profile-label" for="id_icon">Profile Picture: </label>
            <div class="user-image-sel">{{ form.image }}</div>
        </span>
        <div class="form-gap small"></div>

        <span style="display: flex;" class="form-settings-user">
            <label class="create-community-label edit-profile-label" for="id_icon">Profile Banner: </label>
            <div class="user-banner-sel">{{ form.banner }}</div>
        </span>
        <div class="form-gap small"></div>

        <span>
            <button class="community-button p-comm-btn-submit post-btn-submit" type="submit" form="community-create">
                <div class="community-button-text">UPDATE PROFILE</div>
            </button>
        </span>
        
        <div class="error-list">
            {{ form.non_field_errors }}
            <div class="fieldWrapper">
                {{ form.image.errors }}
                {{ form.message }}
            </div>
            <div class="fieldWrapper">
                {{ form.banner.errors }}
                {{ form.message }}
            </div>
            <div class="fieldWrapper">
                {{ form.highlight_color_hex.errors }}
                {{ form.message }}
            </div>
        </div>
    </form>
</div>

templates/users/users_list_min.html
{% load static %}
{% load humanize %}
{% load extra_tags %}

<div class="" style="display:flex; flex-direction: row; flex-wrap: wrap; justify-content: space-between;">
{% for user in users %}
<div class="comm-content-box" onclick=" location.href = '{% url 'profile' user %}'; event.stopPropagation();" style="min-width: 32%">
    
    <div class="comm-content-box-1" style="width: 1rem;">


    </div>

    <div class="comm-content-box-2" style="overflow:hidden; width: 100%">


        <div class="post-title txt-brk" style="display:flex; align-items: center; margin-bottom: 10px;">

            <div class="post-community-image-wrapper" style="float:right; margin-right: 22px; width: 40px; height: 40px; margin-top:3px;">
                <img style="width: 40px; height: 40px; border-radius: 50%; border: 3px solid rgba(255, 255, 255, 0.123);" class="post-community-image post-main-img sdbr" src="{{ user.profile.image.url }}" alt="Community Icon">
            </div>
            <span style="font-size: 18px; display:flex; flex-direction:column; justify-content: center; margin-top: 10px;">
            u/{{ user.username }}<br/>
            <small style="color:#919394; margin-top: 2px; font-weight: normal;">
                    {% with user.posts.count as post_count %}
                        {% if post_count == 1 %}    
                            <strong>1</strong> post
                        {% else %}
                            <strong>{{ post_count | cool_number }}</strong> posts
                        {% endif %}
                    {% endwith %}
            </small>
            </span>

        </div>




    </div>

</div>

{% endfor %}
</div>